package cmd

import (
	"fmt"
	"os"
	"path/filepath"

	"git.byka.wtf/potemsla/YouEye/spine/internal/config"
	"github.com/spf13/cobra"
	"gopkg.in/yaml.v3"
)

var configCmd = &cobra.Command{
	Use:   "config",
	Short: "Manage Spine configuration",
	Long: `Manage Spine configuration files.

Configuration is loaded from multiple sources with the following precedence:
  1. CLI flags (highest priority)
  2. Environment variables (SPINE_*)
  3. Config file (/etc/spine/config.yaml)
  4. Default values (lowest priority)

Examples:
  spine config init       # Generate default configuration file
  spine config show       # Display current effective configuration
  spine config validate   # Validate configuration file syntax`,
}

var configInitCmd = &cobra.Command{
	Use:   "init",
	Short: "Generate default configuration file",
	Long: `Generate a configuration file with default values.

The configuration file will be created at /etc/spine/config.yaml by default.
Use --output to specify a different location.

Example:
  spine config init                         # Create /etc/spine/config.yaml
  spine config init --output ./config.yaml  # Create in current directory`,
	RunE: runConfigInit,
}

var configShowCmd = &cobra.Command{
	Use:   "show",
	Short: "Display current effective configuration",
	Long: `Display the current effective configuration.

This shows the merged configuration from all sources:
  - Default values
  - Config file (if present)
  - Environment variables
  - CLI flags`,
	RunE: runConfigShow,
}

var configValidateCmd = &cobra.Command{
	Use:   "validate",
	Short: "Validate configuration file",
	Long: `Validate the configuration file syntax and values.

This command checks:
  - YAML syntax
  - Required fields
  - Value constraints (e.g., port ranges)`,
	RunE: runConfigValidate,
}

var configOutputPath string

func init() {
	configCmd.AddCommand(configInitCmd)
	configCmd.AddCommand(configShowCmd)
	configCmd.AddCommand(configValidateCmd)

	configInitCmd.Flags().StringVarP(&configOutputPath, "output", "o", "/etc/spine/config.yaml", "Output path for configuration file")
}

func runConfigInit(cmd *cobra.Command, args []string) error {
	// Generate default configuration
	defaults := config.Default()

	// Marshal to YAML with comments
	yamlData, err := yaml.Marshal(defaults)
	if err != nil {
		return fmt.Errorf("failed to generate YAML: %w", err)
	}

	// Add header comment
	header := `# YE-Spine Configuration
# Generated by: spine config init
# Documentation: https://git.byka.wtf/potemsla/YouEye/spine
#
# Configuration precedence (highest to lowest):
#   1. CLI flags (--port, --gitea-url, etc.)
#   2. Environment variables (SPINE_RELEASES_BASE_URL, etc.)
#   3. This config file
#   4. Default values
#
# To use environment variables, replace dots with underscores and prefix with SPINE_
# Example: releases.base_url -> SPINE_RELEASES_BASE_URL
#

`
	content := header + string(yamlData)

	// Create directory if needed
	dir := filepath.Dir(configOutputPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		return fmt.Errorf("failed to create directory %s: %w", dir, err)
	}

	// Check if file exists
	if _, err := os.Stat(configOutputPath); err == nil {
		fmt.Printf("Configuration file already exists: %s\n", configOutputPath)
		fmt.Print("Overwrite? [y/N]: ")
		var response string
		fmt.Scanln(&response)
		if response != "y" && response != "Y" {
			fmt.Println("Aborted.")
			return nil
		}
	}

	// Write configuration file
	if err := os.WriteFile(configOutputPath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write config file: %w", err)
	}

	fmt.Printf("Configuration file created: %s\n", configOutputPath)
	fmt.Println("\nYou can now edit this file to customize your installation.")
	fmt.Println("Common customizations:")
	fmt.Println("  - releases.base_url: Change to your Gitea/GitHub server")
	fmt.Println("  - releases.organization: Your username or organization")
	fmt.Println("  - deployment.control_panel.port: Change from default 3000")
	fmt.Println("  - deployment.container.name: For multi-instance setups")

	return nil
}

func runConfigShow(cmd *cobra.Command, args []string) error {
	// Get the current configuration (already loaded by PersistentPreRunE)
	currentCfg := GetConfig()

	// Show config file path if loaded
	if cfgPath := config.GetConfigFile(); cfgPath != "" {
		fmt.Printf("# Loaded from: %s\n", cfgPath)
	} else {
		fmt.Println("# No config file found, showing defaults")
	}
	fmt.Println()

	// Marshal to YAML
	yamlData, err := yaml.Marshal(currentCfg)
	if err != nil {
		return fmt.Errorf("failed to format configuration: %w", err)
	}

	fmt.Println(string(yamlData))
	return nil
}

func runConfigValidate(cmd *cobra.Command, args []string) error {
	// Get the config file path
	var configPath string
	if cfgFile != "" {
		configPath = cfgFile
	} else if cfgPath := config.GetConfigFile(); cfgPath != "" {
		configPath = cfgPath
	}

	if configPath == "" {
		fmt.Println("No configuration file found.")
		fmt.Println("Configuration files are searched in:")
		fmt.Println("  1. Path specified with --config flag")
		fmt.Println("  2. /etc/spine/config.yaml")
		fmt.Println("  3. ~/.spine/config.yaml")
		fmt.Println("  4. ./config.yaml")
		fmt.Println("\nTo create a configuration file, run: spine config init")
		return nil
	}

	fmt.Printf("Validating: %s\n", configPath)

	// Try to load and validate
	testCfg, err := config.LoadFromFile(configPath)
	if err != nil {
		fmt.Printf("\n❌ Configuration is INVALID\n")
		fmt.Printf("   Error: %v\n", err)
		return err
	}

	// Additional validation checks
	fmt.Println("\nChecking configuration values...")

	// Check releases URL is reachable (optional)
	fmt.Printf("  ✓ releases.base_url: %s\n", testCfg.Releases.BaseURL)
	fmt.Printf("  ✓ releases.organization: %s\n", testCfg.Releases.Organization)
	fmt.Printf("  ✓ deployment.container.name: %s\n", testCfg.Deployment.Container.Name)
	fmt.Printf("  ✓ deployment.control_panel.port: %d\n", testCfg.Deployment.ControlPanel.Port)
	fmt.Printf("  ✓ api.socket_path: %s\n", testCfg.API.SocketPath)
	fmt.Printf("  ✓ logging.level: %s\n", testCfg.Logging.Level)

	fmt.Println("\n✓ Configuration is valid")
	return nil
}
