import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.env.CONTROL_PANEL_ROOT || path.join(import.meta.dirname, '..');
const read = (filename: string) => readFileSync(path.join(root, filename), 'utf8');

test('AI is a personal Settings surface with exact-account controls for every identity user', () => {
  const shell = read('src/components/settings-shell/settings-shell.tsx');
  const page = read('src/app/settings/(shell)/ai/page.tsx');
  const client = read('src/components/settings-shell/ai-client.tsx');
  const native = read('src/components/settings-shell/ai-native-sections.tsx');
  const icon = read('src/components/settings-shell/ai-icon.tsx');
  const picker = read('src/components/settings-shell/ai-model-picker.tsx');
  const shared = read('src/components/settings-shell/ai-shared.tsx');
  const detail = read('src/components/settings-shell/ai-detail-client.tsx');
  assert.match(shell, /href: ['"]\/settings\/ai['"]/);
  assert.match(shell, /label: ['"]AI['"]/);
  assert.doesNotMatch(page, /isAdmin/);
  assert.match(page, /authMethod === 'pam'/);
  for (const label of ['Models', 'Groups', 'Instances', 'Providers', 'Usage', 'Playground']) {
    assert.match(shared, new RegExp(`label: '${label}'`));
  }
  for (const removed of ['Overview', 'Accounts', 'API keys']) {
    assert.doesNotMatch(shared, new RegExp(`label: '${removed}'`));
  }
  assert.match(page, /section="models"/);
  assert.equal(existsSync(path.join(root, 'src/app/settings/(shell)/ai/accounts/[id]/page.tsx')), false);
  assert.equal(existsSync(path.join(root, 'src/app/settings/(shell)/ai/keys/[id]/page.tsx')), false);
  assert.match(client, /providerAccountId: selected\.route\.providerAccountId/);
  assert.match(client, /function useAvailableId/);
  assert.match(client, /items\.some\(\(item\) => item\.id === selected\)/);
  assert.match(detail, /entries\/reorder/);
  assert.match(detail, /duplicateCanonical/);
  assert.match(detail, /Public alias .*required for another route/);
  assert.match(detail, /hiddenAliases\.map/);
  assert.match(detail, /Create as many client credentials as you need/);
  assert.match(detail, /Copy this key now/);
  assert.match(native, /You can add the same provider more than once|Add the same provider more than once/);
  assert.match(native, /oauth\/device\/start/);
  assert.match(native, /userCode/);
  assert.match(native, /Nickname \(optional\)/);
  assert.match(native, /endpoint\?\.mode === 'required'/);
  assert.doesNotMatch(native, /Custom endpoint \(optional\)/);
  assert.match(native, /Official providers keep their official endpoint/);
  assert.match(native, /sort, setSort.*recommended/);
  assert.match(native, /value: 'newest'/);
  assert.match(native, /benchmarkDescriptors.*value: `benchmark:/s);
  assert.match(native, /Recommended consensus/);
  assert.match(native, /coverage.*eligibleSources/);
  assert.match(native, /awaiting benchmark results/i);
  assert.match(native, /modelIconKey \|\| model\.creatorIconKey/);
  assert.match(icon, /@\/assets\/ai-brands\/claude-color\.svg/);
  assert.match(icon, /<Image src=\{file\}/);
  assert.match(icon, /monochromeKeys\.has\(normalized\).*dark:invert/);
  assert.match(icon, /data-icon-kind=\{file && !failed \? 'brand' : 'generic'\}/);
  assert.match(icon, /bg-transparent/);
  assert.doesNotMatch(icon, /rounded-lg border bg-background/);
  assert.match(icon, /kimi\.svg/);
  assert.match(icon, /'xai-grok': grokIcon/);
  assert.doesNotMatch(icon, /src=\{`\/icons\/ai-brands/);
  assert.match(native, /defaultGroup/);
  assert.match(native, /role="listbox" aria-label="Provider"/);
  assert.match(native, /Provider choices open automatically/);
  assert.match(native, /previewEntries\.map/);
  assert.match(native, /data-view="models-list"/);
  assert.match(native, /data-list-row="model"/);
  assert.match(native, /data-view="groups-list"/);
  assert.match(native, /data-list-row="group"/);
  assert.match(native, /data-view="providers-list"/);
  assert.match(native, /data-list-row="provider"/);
  assert.match(client, /instances\.length.*className="grid gap-3 md:grid-cols-2"/s);
  assert.match(client, /Grouped by.*<table/s);
  assert.match(native, /account\.credentialConfigured \? account\.status : 'needs connection'/);
  assert.match(detail, /Provider routes/);
  assert.match(detail, /Observed performance/);
  assert.match(detail, /Benchmarks/);
  assert.match(detail, /Identity and provenance/);
  assert.match(detail, /data-view="group-routes-list"/);
  assert.match(detail, /data-list-row="group-route"/);
  assert.match(detail, /<AIModelPicker label="Model"/);
  assert.match(client, /write me 2 sentences about cool cats\./);
  assert.match(client, /<AIModelPicker label=\{compare \? 'Target A' : 'Target'\}/);
  assert.match(picker, /Search model, creator, provider, alias, or route/);
  assert.match(picker, /ordered like Models/);
});

test('bundled AI SVG brands have a clean-checkout TypeScript module contract', () => {
  const declaration = read('src/types/svg.d.ts');
  assert.match(declaration, /declare module '\*\.svg'/);
  assert.match(declaration, /src: string/);
  assert.match(declaration, /width: number/);
  assert.match(declaration, /height: number/);
});

test('same-origin AI adapter authenticates users server-side and rejects route or CSRF expansion', () => {
  const route = read('src/app/api/ai/[...path]/route.ts');
  const pointer = read('src/lib/pointer/client.ts');
  const tokens = read('src/lib/identity/tokens.ts');
  assert.match(route, /getSession/);
  assert.match(route, /verifyCSRFToken/);
  assert.match(route, /allowedPointerManagementPath/);
  assert.match(route, /pointerManagementFetch/);
  assert.match(route, /upstream\.body/);
  assert.doesNotMatch(route, /upstream\.arrayBuffer/);
  assert.doesNotMatch(route, /request\.headers\.get\(['"]authorization/);
  assert.match(pointer, /authorization: `Bearer \$\{assertion\}`/);
  assert.match(pointer, /new URL\(path, 'http:\/\/pointer\.internal'\)\.pathname/);
  assert.match(pointer, /AI settings require a YouEye user account/);
  assert.match(tokens, /pointer_owner_scope: 'actor'/);
  assert.match(tokens, /sub: user\.id/);
  assert.match(tokens, /setExpirationTime\('2m'\)/);
  assert.match(tokens, /setJti\(randomUUID\(\)\)/);
});

test('Pointer is a managed core service with isolated listeners, database, secrets, update migration, and backup', () => {
  const lifecycle = read('src/lib/pointer/lifecycle.ts');
  const manifests = read('src/lib/infrastructure/manifests.ts');
  const lxdDeployer = read('src/lib/infrastructure/lxd-deployer.ts');
  const definitions = read('src/lib/apps/definitions.ts');
  const backup = read('src/lib/backup/core-backup.ts');
  const postgres = read('src/lib/backup/postgres.ts');
  const staticIps = read('src/lib/incus/static-ips.ts');
  const security = read('src/lib/infrastructure/security-posture.ts');
  const appNetwork = read('src/lib/incus/app-network.ts');
  const spineStaticIps = read('../spine/internal/incus/static_ips.go');
  assert.match(manifests, /containerName: 'youeye-pointer'/);
  assert.match(manifests, /runtime: 'bun'/);
  assert.match(lifecycle, /const POINTER_DATABASE = 'pointer'/);
  assert.match(lifecycle, /MANAGEMENT_PORT=4001/);
  assert.match(lifecycle, /INFERENCE_PORT=4002/);
  assert.match(lifecycle, /PLATFORM_SIGNING_ALGORITHMS=RS256/);
  assert.match(lifecycle, /identity\.externalUrl\}\/oauth\/jwks/);
  assert.doesNotMatch(lifecycle, /application\/o\/jwks/);
  assert.match(lifecycle, /MANAGED_SERVICE_PRINCIPAL_NAME="YouEye managed applications"/);
  assert.match(lifecycle, /umask 077/);
  assert.match(lifecycle, /'\{ :'/);
  assert.match(lifecycle, /\/etc\/youeye-pointer\.env/);
  assert.match(lifecycle, /\/opt\/pointer\/bun/);
  assert.match(lxdDeployer, /signed release artifact/);
  assert.match(lxdDeployer, /test -x .*appDir.*\/bun/);
  assert.doesNotMatch(lxdDeployer, /bun\.sh\/install/);
  assert.match(definitions, /giteaRepo: 'Pointer'/);
  assert.match(definitions, /migrationCommand:/);
  assert.match(definitions, /\/opt\/pointer\/bun \/opt\/pointer\/migrate\.js/);
  assert.match(definitions, /installStyledJsx: false/);
  assert.match(postgres, /'pointer'/);
  assert.match(backup, /'youeye-pointer'/);
  assert.match(backup, /`\$\{YOUEYE_DATA_DIR\}\/pointer\/`/);
  assert.match(staticIps, /'youeye-pointer': 17/);
  assert.match(staticIps, /raw\.dnsmasq/);
  assert.match(security, /Block UI from reaching Pointer directly/);
  assert.match(appNetwork, /block direct Pointer access/);
  assert.match(spineStaticIps, /"youeye-pointer":\s+17/);
});

test('the apex exposes inference only while management remains private and aggregate admin health stays separate', () => {
  const caddy = read('src/lib/caddy/client.ts');
  const admin = read('src/app/api/ai-system/route.ts');
  const adminPage = read('src/app/settings/(shell)/system/ai/page.tsx');
  assert.match(caddy, /path: \['\/v1', '\/v1\/\*', '\/v1beta', '\/v1beta\/\*'\]/);
  const routeSection = caddy.slice(caddy.indexOf('export async function ensurePointerInferenceRoutes'));
  assert.doesNotMatch(routeSection.slice(0, routeSection.indexOf('/**', 20)), /\/api\/|4001/);
  assert.match(admin, /requireAdmin/);
  assert.match(admin, /body\.status === 'ready'/);
  assert.match(admin, /database:/);
  assert.match(admin, /backup: 'included_in_core_backup'/);
  assert.doesNotMatch(admin, /provider-accounts|\/api\/keys|\/api\/groups|\/api\/instances/);
  assert.match(adminPage, /session\?\.isAdmin/);
});
