import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import path from 'node:path';
import test from 'node:test';

const root = process.env.CONTROL_PANEL_ROOT || path.join(import.meta.dirname, '..');
const read = (filename: string) => readFileSync(path.join(root, filename), 'utf8');

test('platform backup uses shared protected staging and exact structured archives', () => {
  const packageJson = JSON.parse(read('package.json')) as { scripts?: { build?: string } };
  const nextConfig = read('next.config.ts');
  const productionBuild = read('scripts/build-production.js');
  const workspace = read('src/lib/backup/workspace.ts');
  const core = read('src/lib/backup/core-backup.ts');
  const app = read('src/lib/backup/app-backup.ts');
  const postgres = read('src/lib/backup/postgres.ts');
  assert.match(workspace, /BACKUP_STAGING_ROOT = path\.join\(BACKUP_ROOT, '\.staging'\)/);
  assert.match(workspace, /!source\.startsWith\(`\$\{BACKUP_ROOT\}\//);
  assert.match(core, /backup_type: 'core'/);
  assert.match(core, /volume_mappings: volumeMappings/);
  assert.match(postgres, /PLATFORM_DATABASES = \['youeye', 'youeye_ui', 'pointer'\]/);
  assert.match(core, /for \(const dbName of PLATFORM_DATABASES\)/);
  assert.match(core, /dbName === 'pointer'.*platformDatabaseExists/s);
  assert.match(core, /Dumping YouEye ID, UI, and AI databases/);
  assert.doesNotMatch(core, /youeye-authentik/);
  assert.match(packageJson.scripts?.build || '', /node scripts\/build-production\.js/);
  assert.match(productionBuild, /git\('rev-parse', 'HEAD'\)/);
  assert.match(productionBuild, /process\.env\.YOUEYE_SOURCE_COMMIT/);
  assert.match(productionBuild, /does not match the checked-out source commit/);
  assert.match(productionBuild, /when Git metadata is absent/);
  assert.match(productionBuild, /Refusing to produce a release build from modified tracked source/);
  assert.match(productionBuild, /youeye-control-panel-build-v1/);
  assert.match(productionBuild, /NEXT_SERVER_ACTIONS_ENCRYPTION_KEY: actionKey/);
  assert.match(productionBuild, /\.previewinfo/);
  assert.match(productionBuild, /\.rscinfo/);
  assert.match(productionBuild, /fs\.rmSync\(nextDir/);
  assert.match(nextConfig, /generateBuildId/);
  assert.match(nextConfig, /\^\[0-9a-f\]\{40\}\$/);
  assert.match(app, /backup_type: 'app'/);
  assert.match(app, /app_id: appId/);
  assert.match(core, /PLATFORM_POSTGRES_ADMIN/);
  assert.match(app, /installMeta\.databaseName/);
  assert.match(postgres, /PLATFORM_POSTGRES_ADMIN = 'youeye'/);
  assert.match(postgres, /incusUploadFile/);
  assert.match(postgres, /mode: '0600'/);
  assert.match(postgres, /'ON_ERROR_STOP=1'/);
  assert.doesNotMatch(`${core}\n${app}\n${postgres}`, /pg_dump -U postgres|echo '\$\{b64\}'|PASSWORD.*execCommand/);
});

test('backup and restore APIs require admin, CSRF, body-only passphrases, and confirmation', () => {
  const create = read('src/app/api/backup/core/route.ts');
  const restore = read('src/app/api/backup/restore/route.ts');
  const settingsRestore = read('src/app/settings/api/backup/restore/route.ts');
  const cli = read('../spine/internal/cmd/backup.go');
  const controlClient = read('../spine/internal/controlapi/client.go');
  for (const route of [create, restore]) {
    assert.match(route, /session\?\.isAdmin/);
    assert.match(route, /verifyCSRFToken/);
    assert.match(route, /request\.json/);
    assert.doesNotMatch(route, /searchParams.*passphrase/);
  }
  assert.match(restore, /body\.confirm !== true/);
  assert.match(restore, /withRestoreLock/);
  assert.match(restore, /restartControl\(5\)/);
  assert.match(restore, /validateRestoreOperationId/);
  assert.match(restore, /writeRestoreStatus/);
  assert.match(restore, /export async function GET/);
  assert.match(restore, /let streamOpen = true/);
  assert.match(restore, /try \{\s*controller\.enqueue\(encoder\.encode\(chunk\)\)/);
  assert.match(restore, /cancel\(\) \{\s*streamOpen = false/);
  assert.match(settingsRestore, /export \{ GET, POST \} from '@\/app\/api\/backup\/restore\/route'/);
  assert.match(read('src/lib/backup/platform-backup.ts'), /RESTORE_STATUS_ROOT[\s\S]*operationId.*\.json/);
  assert.match(cli, /newRestoreOperationID/);
  assert.match(cli, /waitForRestoreCompletion/);
  assert.match(cli, /"operationId": operationID/);
  assert.match(controlClient, /jsonStr == "\[DONE\]"/);
});

test('Backups Settings is a real role-gated create, history, and restore surface', () => {
  const page = read('src/app/settings/(shell)/backup/page.tsx');
  const shell = read('src/components/settings-shell/settings-shell.tsx');
  const client = read('src/components/settings-shell/backup-client.tsx');
  assert.match(page, /session\?\.isAdmin/);
  assert.match(page, /<BackupClient/);
  assert.match(shell, /label: "Backups"/);
  assert.match(client, /\/settings\/api\/backup\/core/);
  assert.match(client, /\/settings\/api\/backup\/restore/);
  assert.match(client, /type="password"/);
  assert.match(client, /ConfirmDialog/);
  assert.match(client, /crypto\.randomUUID\(\)/);
  assert.match(client, /waitForRestore/);
  assert.match(client, /Server interface is restarting/);
  assert.doesNotMatch(client, /passphrase.*searchParams/);
});

test('restore applies encrypted core and app volume maps before completion', () => {
  const full = read('src/lib/backup/full-restore.ts');
  const app = read('src/lib/backup/app-restore.ts');
  const postgres = read('src/lib/backup/postgres.ts');
  const spine = read('src/lib/spine/client.ts');
  assert.match(spine, /Promise<\{ staging_dir: string; message: string \}>/);
  assert.doesNotMatch(`${full}\n${app}`, /restoreArchive[\s\S]{0,300}\.status/);
  assert.match(full, /applyBackupVolumes\(coreStagingDir\)/);
  assert.match(full, /throw new Error\(`No core backup found/);
  assert.match(full, /RESTORE_CONTAINER_START_ATTEMPTS = 5/);
  assert.match(full, /for \(const container of quiesced\)/);
  assert.match(full, /runningContainers\(\[container\]\)[\s\S]{0,40}\.includes\(container\)/);
  assert.doesNotMatch(full, /Promise\.allSettled\(quiesced/);
  assert.match(app, /applyBackupVolumes\(stagingDir\)/);
  assert.match(full, /unexpected database dump/);
  assert.match(full, /isPlatformDatabase\(dbName\)/);
  assert.match(full, /replacePlatformDatabase/);
  assert.match(app, /replacePlatformAppDatabase/);
  assert.match(postgres, /replacePlatformAppDatabase[\s\S]*await applyPostgresDump\(\{[\s\S]*database,[\s\S]*user,[\s\S]*dump: options\.dump/);
  assert.match(app, /restoreOwnPostgresDatabase/);
  assert.match(app, /validateOwnPostgresStorageContract/);
  assert.match(app, /Restored the encrypted database dump/);
  assert.match(app, /containerName !== container/);
  assert.match(postgres, /DROP DATABASE IF EXISTS \$\{databaseIdentifier\}/);
  assert.match(app, /postInstallOwnDatabaseRestore/);
  assert.match(app, /waitForOperation\(response\.operation, 60\)/);
  assert.match(app, /startContainerAfterRestore/);
  assert.match(app, /if \(existsSync\(ownDumpPath\)\)/);
  assert.match(app, /Shared databases and volumes were restored before install/);
  assert.doesNotMatch(app, /Promise\.allSettled\(stoppedContainers/);
  assert.match(postgres, /DROP DATABASE IF EXISTS/);
  assert.match(postgres, /CREATE DATABASE/);
  assert.doesNotMatch(`${full}\n${app}`, /execShell|base64.*psql|-U postgres/);
  assert.doesNotMatch(full, /youeye-authentik|restart-authentik/);
  assert.match(app, /invalid own-database restore metadata/);
});
