'use client';

import Link from 'next/link';
import { useCallback, useEffect, useMemo, useState } from 'react';
import { ArrowDown, ArrowLeft, ArrowUp, Check, ChevronDown, Copy, ExternalLink, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { Alert } from '@/components/ui/alert';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { ConfirmDialog } from '@/components/ui/confirm-dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { AIIcon } from './ai-icon';
import { AIModelPicker } from './ai-model-picker';
import { AIShell, Empty, Loading, MetricCards, RecentUsageTable, Status } from './ai-shared';
import {
  aiApi,
  formatPrice,
  formatTokens,
  type Account,
  type AccountDetail,
  type APIKey,
  type CatalogModel,
  type CatalogResponse,
  type Group,
  type GroupDetail,
  type GroupEntry,
  type Instance,
  type InstanceDetail,
  type Stats,
} from './ai-types';

type DetailKind = 'model' | 'provider' | 'group' | 'instance';

export function AIDetailClient({ kind, id }: { kind: DetailKind; id: string }) {
  const section = kind === 'model' ? 'models' : kind === 'provider' ? 'providers' : kind === 'group' ? 'groups' : 'instances';
  return <AIShell section={section}>
    {kind === 'model' && <ModelDetail slug={id} />}
    {kind === 'provider' && <AccountDetails id={id} />}
    {kind === 'group' && <NativeGroupDetails id={id} />}
    {kind === 'instance' && <NativeInstanceDetails id={id} />}
  </AIShell>;
}

function DetailHeader({ back, eyebrow, title, description, actions }: { back: string; eyebrow: string; title: React.ReactNode; description?: string | null; actions?: React.ReactNode }) {
  return <div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><Button asChild variant="ghost" size="sm" className="-ml-2 mb-2"><Link href={back}><ArrowLeft className="size-4" />Back to {eyebrow}</Link></Button><h1 className="text-2xl font-semibold tracking-tight">{title}</h1>{description && <p className="mt-2 max-w-3xl text-sm leading-6 text-muted-foreground">{description}</p>}</div>{actions && <div className="flex shrink-0 flex-wrap gap-2">{actions}</div>}</div>;
}

function ModelDetail({ slug }: { slug: string }) {
  const [model, setModel] = useState<(CatalogModel & { sources: Array<{ sourceId: string; status: string; stale: boolean; fetchedAt: string | null }> }) | null>(null);
  const [groups, setGroups] = useState<Group[]>([]);
  const [accounts, setAccounts] = useState<Account[]>([]);
  const [stats, setStats] = useState<Stats | null>(null);
  const [groupId, setGroupId] = useState(''); const [routeKey, setRouteKey] = useState(''); const [accountId, setAccountId] = useState('');
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [nextModel, nextGroups, nextAccounts] = await Promise.all([aiApi<typeof model>(`/catalog/detail?slug=${encodeURIComponent(slug)}`), aiApi<Group[]>('/groups'), aiApi<Account[]>('/provider-accounts')]); if (!nextModel) throw new Error('Model not found'); setModel(nextModel); setGroups(nextGroups); setAccounts(nextAccounts); setGroupId((current) => current || nextGroups.find((item) => item.isDefault)?.id || nextGroups[0]?.id || ''); setRouteKey((current) => current || nextModel.providers.find((item) => item.available)?.providerModelKey || ''); aiApi<Stats>(`/stats/model/${encodeURIComponent(nextModel.id)}?days=30`).then(setStats).catch(() => setStats(null)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Model unavailable'); } finally { setLoading(false); } }, [slug]);
  useEffect(() => { void load(); }, [load]);
  const route = model?.providers.find((item) => item.providerModelKey === routeKey);
  const matchingAccounts = useMemo(() => route ? accounts.filter((account) => route.accounts.some((item) => item.id === account.id)) : [], [accounts, route]);
  useEffect(() => { setAccountId((current) => matchingAccounts.some((item) => item.id === current) ? current : matchingAccounts[0]?.id || ''); }, [routeKey, matchingAccounts]);
  async function add() { if (!model || !groupId || !routeKey || !accountId) return; setBusy(true); setError(''); try { await aiApi(`/groups/${groupId}/entries`, { method: 'POST', body: JSON.stringify({ catalogEntityId: model.id, providerModelKey: routeKey, providerAccountId: accountId }) }); setNotice(`${model.name} added to ${groups.find((item) => item.id === groupId)?.name || 'group'}`); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Could not add model'); } finally { setBusy(false); } }
  if (loading) return <Loading />;
  if (error && !model) return <Alert variant="destructive">{error}</Alert>;
  if (!model) return null;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/models" eyebrow="models" title={<span className="flex items-center gap-3"><AIIcon iconKey={model.modelIconKey || model.creatorIconKey} name={model.name} className="size-11" />{model.name}</span>} description={model.description} actions={<><Status value={model.available} label={model.available ? 'Available to you' : 'No connected route'} />{model.organization?.websiteUrl && <Button asChild variant="outline" size="sm"><a href={model.organization.websiteUrl} target="_blank" rel="noreferrer">Creator site<ExternalLink className="size-4" /></a></Button>}</>} />{error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-6"><Fact label="Creator" value={model.creator || 'Unknown'} /><Fact label="Recommended" value={model.recommendedRanking ? `#${model.recommendedRanking.rank} · ${model.recommendedRanking.coverage}/${model.recommendedRanking.eligibleSources} sources` : 'Awaiting benchmark results'} /><Fact label="Released" value={model.releasedAt ? new Date(model.releasedAt).toLocaleDateString() : 'Unknown'} /><Fact label="Context window" value={formatTokens(model.contextWindow)} /><Fact label="Maximum output" value={formatTokens(model.maxOutput)} /><Fact label="Reference price" value={`${formatPrice(model.referencePricing.input)} in / ${formatPrice(model.referencePricing.output)} out`} /></div>
    <Card className="gap-4 p-5"><div><h2 className="font-semibold">Capabilities</h2><p className="mt-1 text-sm text-muted-foreground">Capabilities are catalog evidence; individual provider routes may differ.</p></div><div className="flex flex-wrap gap-2">{Object.entries(model.capabilities).map(([name, enabled]) => <Badge key={name} variant={enabled ? 'default' : 'secondary'}>{name}: {enabled ? 'yes' : 'not declared'}</Badge>)}</div></Card>
    <Card className="gap-4 p-5"><div><h2 className="font-semibold">Add to a model group</h2><p className="mt-1 text-sm text-muted-foreground">Applications see “{model.name}”. The provider and account remain private routing details.</p></div>{groups.length === 0 ? <Empty title="No groups" description="Create a model group first." action={<Button asChild><Link href="/settings/ai/groups">Create group</Link></Button>} /> : <div className="grid gap-3 md:grid-cols-3"><Choice label="Group" value={groupId} onChange={setGroupId} items={groups.map((item) => ({ value: item.id, label: item.name }))} /><Choice label="Provider route" value={routeKey} onChange={setRouteKey} items={model.providers.filter((item) => item.available).map((item) => ({ value: item.providerModelKey, label: `${item.providerName} · ${item.rawModelId}` }))} /><Choice label="Account" value={accountId} onChange={setAccountId} items={matchingAccounts.map((item) => ({ value: item.id, label: item.nickname || `${item.providerName} · ${item.id.slice(-6)}` }))} /></div>}<Button className="self-start" disabled={busy || !groupId || !routeKey || !accountId} onClick={() => void add()}>Add model</Button></Card>
    <div><h2 className="mb-3 font-semibold">Provider routes</h2><Card className="block overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-sm"><thead className="border-b bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Provider</th><th className="px-4 py-3 font-medium">Upstream model</th><th className="px-4 py-3 font-medium">Accounts</th><th className="px-4 py-3 font-medium">Price in / out</th><th className="px-4 py-3 font-medium">Context / output</th><th className="px-4 py-3 font-medium">Capabilities</th></tr></thead><tbody className="divide-y">{model.providers.map((item) => <tr key={item.providerModelKey}><td className="px-4 py-3"><strong>{item.providerName}</strong><div className="mt-1"><Status value={item.available} /></div></td><td className="px-4 py-3 font-mono text-xs">{item.rawModelId}</td><td className="px-4 py-3">{item.accounts.length ? <div className="flex flex-wrap gap-1">{item.accounts.map((account) => <Badge key={account.id} variant="secondary">{account.nickname || account.id.slice(-6)}</Badge>)}</div> : <span className="text-muted-foreground">None connected</span>}</td><td className="px-4 py-3 tabular-nums text-muted-foreground">{formatPrice(item.pricing.input)} / {formatPrice(item.pricing.output)}</td><td className="px-4 py-3 tabular-nums text-muted-foreground">{formatTokens(item.contextWindow)} / {formatTokens(item.maxOutput)}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{Object.entries(item.capabilities).filter(([, enabled]) => enabled).map(([name]) => <Badge key={name} variant="secondary">{name}</Badge>)}</div></td></tr>)}</tbody></table></div></Card></div>
    {stats && <div><h2 className="mb-3 font-semibold">Observed performance · last 30 days</h2><MetricCards stats={stats} /></div>}
    <div className="grid gap-4 lg:grid-cols-2"><Card className="gap-3 p-5"><div><h2 className="font-semibold">Benchmarks</h2><p className="mt-1 text-xs text-muted-foreground">Recommended averages normalized general-source percentiles. Specialist sources remain independent.</p></div>{model.benchmarks.length ? <div className="divide-y rounded-md border">{model.benchmarks.map((item) => <div key={item.id} className="flex items-center justify-between gap-3 p-3"><div className="min-w-0"><strong className="text-sm">{item.presentation.label}</strong><p className="truncate text-xs text-muted-foreground">{item.provenance.source} · {item.provenance.license} · fetched {new Date(item.fetchedAt).toLocaleDateString()}</p></div><div className="shrink-0 text-right"><strong>{item.presentation.score ?? '—'} {item.presentation.unit}</strong>{item.presentation.effectiveRank != null && <p className="text-xs text-muted-foreground">Rank {item.presentation.effectiveRank}{item.presentation.rankDerived ? ' · derived' : ''} of {item.presentation.population}</p>}</div></div>)}</div> : <p className="text-sm text-muted-foreground">No benchmark evidence is attached to this model.</p>}</Card><Card className="gap-3 p-5"><h2 className="font-semibold">Identity and provenance</h2><dl className="grid gap-3 text-sm"><FactRow label="Canonical ID" value={model.id} mono /><FactRow label="Slug" value={model.slug} mono /><FactRow label="Metadata source" value={model.metadataSource} /><FactRow label="Fetched" value={model.metadataFetchedAt ? new Date(model.metadataFetchedAt).toLocaleString() : 'Unknown'} /></dl><div><h3 className="mb-2 text-sm font-medium">Aliases</h3>{model.aliases.length ? <div className="flex flex-wrap gap-1">{model.aliases.map((item) => <Badge key={`${item.source}:${item.alias}`} variant="secondary">{item.alias} · {item.source}</Badge>)}</div> : <p className="text-sm text-muted-foreground">No aliases recorded.</p>}</div></Card></div>
  </div>;
}

function AccountDetails({ id }: { id: string }) {
  const [account, setAccount] = useState<AccountDetail | null>(null); const [stats, setStats] = useState<Stats | null>(null); const [nickname, setNickname] = useState(''); const [endpoint, setEndpoint] = useState(''); const [apiKey, setApiKey] = useState(''); const [modelQuery, setModelQuery] = useState(''); const [modelPage, setModelPage] = useState(0); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); setError(''); try { const next = await aiApi<AccountDetail>(`/provider-accounts/${encodeURIComponent(id)}`); setAccount(next); setNickname(next.nickname || ''); setEndpoint(next.baseUrl || ''); aiApi<Stats>(`/stats/account/${encodeURIComponent(id)}?days=30`).then(setStats).catch(() => setStats(null)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Account unavailable'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function work(action: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setNotice(''); try { await action(); setNotice(message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Account update failed'); } finally { setBusy(false); } }
  if (loading) return <Loading />; if (!account) return <Alert variant="destructive">{error || 'Account not found'}</Alert>;
  const normalizedQuery = modelQuery.trim().toLocaleLowerCase();
  const matchingModels = normalizedQuery ? account.models.filter((model) => `${model.name} ${model.rawModelId}`.toLocaleLowerCase().includes(normalizedQuery)) : account.models;
  const pageSize = 50;
  const pageCount = Math.max(1, Math.ceil(matchingModels.length / pageSize));
  const safePage = Math.min(modelPage, pageCount - 1);
  const visibleModels = matchingModels.slice(safePage * pageSize, (safePage + 1) * pageSize);
  return <div className="space-y-6"><DetailHeader back="/settings/ai/providers" eyebrow="providers" title={account.displayName} description={`${account.provider.name} · ${account.provider.type}`} actions={<Status value={account.credentialConfigured ? account.status : 'needs connection'} />} />{error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Provider" value={account.provider.name} /><Fact label="Authentication" value={account.provider.authType} /><Fact label="Models" value={String(account.models.length)} /><Fact label="Endpoint" value={account.baseUrl || 'Official provider endpoint'} /></div>
    <Card className="gap-4 p-5"><div><h2 className="font-semibold">Account settings</h2><p className="mt-1 text-sm text-muted-foreground">Nickname is optional. Leave it blank to use the provider name with an automatic suffix when needed.</p></div><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="account-nickname">Nickname (optional)</Label><Input id="account-nickname" value={nickname} onChange={(event) => setNickname(event.target.value)} /></div>{account.endpoint?.mode === 'required' && <div className="space-y-2"><Label htmlFor="account-endpoint">{account.endpoint.label || 'API endpoint'}</Label><Input id="account-endpoint" value={endpoint} onChange={(event) => setEndpoint(event.target.value)} /></div>}<div className="space-y-2"><Label htmlFor="account-api-key">Replace API key (optional)</Label><Input id="account-api-key" type="password" autoComplete="off" value={apiKey} onChange={(event) => setApiKey(event.target.value)} /></div></div><div className="flex flex-wrap gap-2"><Button disabled={busy || (account.endpoint?.mode === 'required' && !endpoint.trim())} onClick={() => void work(() => aiApi(`/provider-accounts/${id}`, { method: 'PUT', body: JSON.stringify({ nickname: nickname.trim() || null, ...(account.endpoint?.mode === 'required' ? { baseUrl: endpoint.trim() } : {}), ...(apiKey ? { apiKey } : {}) }) }), 'Account settings saved')}><Save className="size-4" />Save</Button><Button variant="outline" disabled={busy || !account.credentialConfigured} onClick={() => void work(() => aiApi(`/provider-accounts/${id}/test`, { method: 'POST' }), 'Connection works')}>Test connection</Button><Button variant="outline" disabled={busy || !account.credentialConfigured} onClick={() => void work(() => aiApi(`/provider-accounts/${id}/sync`, { method: 'POST' }), 'Models synced')}><RefreshCw className="size-4" />Sync models</Button></div></Card>
    <div><div className="mb-3 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><h2 className="font-semibold">Models reported by this account</h2>{account.models.length > 0 && <p className="mt-1 text-xs text-muted-foreground">{matchingModels.length.toLocaleString()} of {account.models.length.toLocaleString()} models</p>}</div>{account.models.length > 0 && <Input className="sm:max-w-xs" aria-label="Search account models" placeholder="Search models or upstream IDs" value={modelQuery} onChange={(event) => { setModelQuery(event.target.value); setModelPage(0); }} />}</div>{account.models.length ? <>{matchingModels.length ? <Card className="block overflow-hidden p-0"><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-sm"><thead className="border-b bg-muted/40 text-left text-xs text-muted-foreground"><tr><th className="px-4 py-3 font-medium">Model</th><th className="px-4 py-3 font-medium">Upstream ID</th><th className="px-4 py-3 font-medium">Context / output</th><th className="px-4 py-3 font-medium">Input / output</th><th className="px-4 py-3 font-medium">Capabilities</th></tr></thead><tbody className="divide-y">{visibleModels.map((model) => <tr key={model.providerModelKey}><td className="px-4 py-3">{model.slug ? <Link href={`/settings/ai/models/${encodeURIComponent(model.slug)}`} className="font-medium hover:underline">{model.name}</Link> : <strong>{model.name}</strong>}</td><td className="px-4 py-3 font-mono text-xs">{model.rawModelId}</td><td className="px-4 py-3">{formatTokens(model.contextWindow)} / {formatTokens(model.maxOutput)}</td><td className="px-4 py-3">{formatPrice(model.inputPrice)} / {formatPrice(model.outputPrice)}</td><td className="px-4 py-3"><div className="flex flex-wrap gap-1">{model.supportsTools && <Badge variant="secondary">tools</Badge>}{model.supportsVision && <Badge variant="secondary">vision</Badge>}{model.supportsStreaming && <Badge variant="secondary">streaming</Badge>}</div></td></tr>)}</tbody></table></div></Card> : <Empty title="No matching models" description="Try another model name or upstream ID." />}{matchingModels.length > pageSize && <div className="mt-3 flex items-center justify-between gap-3"><span className="text-xs text-muted-foreground">Page {safePage + 1} of {pageCount}</span><div className="flex gap-2"><Button variant="outline" size="sm" disabled={safePage === 0} onClick={() => setModelPage((current) => Math.max(0, current - 1))}>Previous</Button><Button variant="outline" size="sm" disabled={safePage >= pageCount - 1} onClick={() => setModelPage((current) => Math.min(pageCount - 1, current + 1))}>Next</Button></div></div>}</> : <Empty title="No synced models" description="Test the connection, then sync models from this account." />}</div>{stats && <div><h2 className="mb-3 font-semibold">Account usage · last 30 days</h2><MetricCards stats={stats} /></div>}
  </div>;
}

function NativeGroupDetails({ id }: { id: string }) {
  const [group, setGroup] = useState<GroupDetail | null>(null);
  const [models, setModels] = useState<CatalogModel[]>([]);
  const [name, setName] = useState('');
  const [addOpen, setAddOpen] = useState(false);
  const [modelId, setModelId] = useState('');
  const [routeChoice, setRouteChoice] = useState('');
  const [alias, setAlias] = useState('');
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [deleteEntry, setDeleteEntry] = useState<GroupEntry | null>(null);
  const [editingEntryId, setEditingEntryId] = useState('');

  const load = useCallback(async () => {
    setLoading(true); setError('');
    try {
      const [nextGroup, first] = await Promise.all([
        aiApi<GroupDetail>(`/groups/${encodeURIComponent(id)}`),
        aiApi<CatalogResponse>('/catalog?availability=available&sort=recommended&page=1&pageSize=100'),
      ]);
      const pages = Math.ceil(first.total / first.pageSize);
      const rest = pages > 1 ? await Promise.all(Array.from({ length: pages - 1 }, (_, index) => aiApi<CatalogResponse>(`/catalog?availability=available&sort=recommended&page=${index + 2}&pageSize=100`))) : [];
      const orderedModels = [first, ...rest].flatMap((page) => page.items);
      setGroup(nextGroup); setName(nextGroup.name); setModels(orderedModels);
      setModelId((current) => orderedModels.some((model) => model.id === current) ? current : orderedModels[0]?.id || '');
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Group unavailable'); }
    finally { setLoading(false); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);

  const selectedModel = models.find((model) => model.id === modelId);
  const modelOptions = useMemo(() => models.map((model) => ({
    value: model.id,
    modelName: model.name,
    creator: model.creator,
    modelIconKey: model.modelIconKey || model.creatorIconKey,
    aliases: model.aliases.map((item) => item.alias),
  })), [models]);
  const routeChoices = useMemo(() => selectedModel?.providers.filter((route) => route.available).flatMap((route) => route.accounts.map((account) => ({ value: `${route.providerModelKey}\u0000${account.id}`, label: `${route.providerName} · ${account.nickname || account.id.slice(-6)} · ${route.rawModelId}` }))) || [], [selectedModel]);
  const duplicateCanonical = Boolean(group?.entries.some((entry) => entry.catalogEntityId === modelId));
  useEffect(() => { setRouteChoice((current) => routeChoices.some((choice) => choice.value === current) ? current : routeChoices[0]?.value || ''); }, [modelId, routeChoices]);

  async function work(action: () => Promise<unknown>, message: string) {
    setBusy(true); setError(''); setNotice('');
    try { await action(); setNotice(message); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Group update failed'); }
    finally { setBusy(false); }
  }
  async function reorder(index: number, direction: -1 | 1) {
    if (!group) return; const entries = [...group.entries]; const target = index + direction;
    if (target < 0 || target >= entries.length) return;
    [entries[index], entries[target]] = [entries[target], entries[index]];
    await work(() => aiApi(`/groups/${id}/entries/reorder`, { method: 'PUT', body: JSON.stringify({ entryIds: entries.map((entry) => entry.id) }) }), 'Model order updated');
  }
  if (loading) return <Loading />;
  if (!group) return <Alert variant="destructive">{error || 'Group not found'}</Alert>;
  const enabledCount = group.entries.filter((entry) => entry.enabled).length;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/groups" eyebrow="groups" title={group.name} description="Ordered public model names and their private provider-account routes." actions={<>{group.isDefault && <Badge>Default</Badge>}<Status value={enabledCount > 0} label={`${enabledCount} enabled`} /></>} />
    {error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <Card className="gap-3 p-5"><div><h2 className="font-semibold">Group settings</h2><p className="mt-1 text-sm text-muted-foreground">The first three enabled entries also receive hidden big/medium/small, opus/sonnet/haiku, and default/secondary/utility aliases in order.</p></div><div className="flex flex-col gap-2 sm:flex-row"><Input aria-label="Group name" value={name} onChange={(event) => setName(event.target.value)} /><Button disabled={busy || !name.trim() || name.trim() === group.name} onClick={() => void work(() => aiApi(`/groups/${id}`, { method: 'PUT', body: JSON.stringify({ name: name.trim() }) }), 'Group renamed')}><Save className="size-4" />Save</Button>{!group.isDefault && <Button variant="outline" disabled={busy} onClick={() => void work(() => aiApi(`/groups/${id}/set-default`, { method: 'PUT' }), 'Default group updated')}>Make default</Button>}</div></Card>
    <div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Model routes</h2><Popover open={addOpen} onOpenChange={setAddOpen}><PopoverTrigger asChild><Button><Plus className="size-4" />Add model</Button></PopoverTrigger><PopoverContent className="w-[min(32rem,calc(100vw-2rem))] space-y-4 p-4"><div><strong className="text-sm">Add a model route</strong><p className="mt-1 text-xs text-muted-foreground">Models follow the exact Recommended order from Models. Search includes names, creators, aliases, providers, and upstream routes.</p></div><AIModelPicker label="Model" value={modelId} onChange={(value) => { setModelId(value); setAlias(''); }} options={modelOptions} /><Choice label="Provider account" value={routeChoice} onChange={setRouteChoice} items={routeChoices} /><div className="space-y-2"><Label htmlFor="group-entry-alias">Public alias {duplicateCanonical ? '(required for another route)' : '(optional)'}</Label><Input id="group-entry-alias" value={alias} onChange={(event) => setAlias(event.target.value)} placeholder={duplicateCanonical ? `A unique name for this ${selectedModel?.name || 'model'} route` : selectedModel?.name} /><p className="text-xs text-muted-foreground">Names must be unique in this group and cannot use Pointer&apos;s hidden routing aliases.</p></div><div className="flex justify-end gap-2"><Button variant="ghost" size="sm" onClick={() => setAddOpen(false)}>Cancel</Button><Button size="sm" disabled={busy || !modelId || !routeChoice || (duplicateCanonical && !alias.trim())} onClick={() => { const [providerModelKey, providerAccountId] = routeChoice.split('\u0000'); void work(async () => { await aiApi(`/groups/${id}/entries`, { method: 'POST', body: JSON.stringify({ catalogEntityId: modelId, providerModelKey, providerAccountId, ...(alias.trim() ? { alias: alias.trim() } : {}) }) }); setAddOpen(false); setAlias(''); }, 'Model route added'); }}>Add model</Button></div></PopoverContent></Popover></div>
    {group.entries.length ? <div data-view="group-routes-list" className="divide-y overflow-hidden rounded-xl border bg-card">{group.entries.map((entry, index) => {
      const catalog = models.find((model) => model.id === entry.catalogEntityId);
      const routes = catalog?.providers.filter((route) => route.available).flatMap((route) => route.accounts.map((account) => ({ value: `${route.providerModelKey}\u0000${account.id}`, label: `${route.providerName} · ${account.nickname || account.id.slice(-6)}` }))) || [];
      const currentRoute = entry.providerModelKey && entry.providerAccountId ? `${entry.providerModelKey}\u0000${entry.providerAccountId}` : '';
      const editing = editingEntryId === entry.id;
      return <div key={entry.id} data-list-row="group-route" className="min-w-0">
        <div className="grid min-h-16 min-w-0 grid-cols-[auto_1fr_auto] items-center gap-2 px-3 py-2.5 md:grid-cols-[64px_minmax(190px,1.1fr)_minmax(180px,1fr)_minmax(150px,.8fr)_110px_40px] md:gap-3">
          <div className="flex items-center gap-0.5"><span className="w-5 text-center text-xs tabular-nums text-muted-foreground">{index + 1}</span><div className="flex flex-col"><Button variant="ghost" size="icon" className="size-6" disabled={busy || index === 0} onClick={() => void reorder(index, -1)} aria-label={`Move ${entry.modelName} up`}><ArrowUp className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-6" disabled={busy || index === group.entries.length - 1} onClick={() => void reorder(index, 1)} aria-label={`Move ${entry.modelName} down`}><ArrowDown className="size-3.5" /></Button></div></div>
          <div className="flex min-w-0 items-center gap-2.5"><AIIcon className="size-7" iconKey={entry.modelIconKey} name={entry.modelName} /><div className="min-w-0">{entry.modelSlug ? <Link href={`/settings/ai/models/${encodeURIComponent(entry.modelSlug)}`} className="block truncate text-sm font-semibold hover:underline">{entry.alias || entry.modelName}</Link> : <strong className="block truncate text-sm">{entry.alias || entry.modelName}</strong>}<p className="truncate text-[11px] text-muted-foreground">{entry.modelName} · <span className="font-mono">{entry.rawModelId}</span></p></div></div>
          <div className="hidden min-w-0 items-center gap-2 md:flex"><AIIcon className="size-6" iconKey={entry.providerIconKey} name={entry.providerName} /><div className="min-w-0"><p className="truncate text-sm font-medium">{entry.providerName}</p><p className="truncate text-[11px] text-muted-foreground">{entry.providerAccountNickname || entry.providerAccountId?.slice(-6) || 'No account'}</p></div></div>
          <div className="col-span-2 ml-14 flex min-w-0 flex-wrap gap-1 md:col-span-1 md:ml-0">{entry.hiddenAliases.length ? entry.hiddenAliases.map((hidden) => <Badge key={hidden} variant="secondary" className="px-1.5 py-0 text-[10px]">{hidden}</Badge>) : <span className="text-xs text-muted-foreground">No hidden aliases</span>}</div>
          <div className="hidden md:block"><Status value={entry.enabled && entry.providerAvailable} label={!entry.enabled ? 'Disabled' : entry.providerAvailable ? 'Ready' : 'Unavailable'} />{entry.needsReview && <Badge variant="destructive" className="mt-1">Review</Badge>}</div>
          <Button variant="ghost" size="icon" className="row-span-2 size-8 md:row-span-1" onClick={() => setEditingEntryId(editing ? '' : entry.id)} aria-expanded={editing} aria-label={`${editing ? 'Close' : 'Edit'} ${entry.alias || entry.modelName}`}><ChevronDown className={`size-4 transition-transform ${editing ? 'rotate-180' : ''}`} /></Button>
        </div>
        {editing && <div className="grid gap-3 border-t bg-muted/20 px-4 py-3 md:grid-cols-2"><div className="space-y-2"><Label htmlFor={`alias-${entry.id}`}>Public name / alias</Label><Input id={`alias-${entry.id}`} defaultValue={entry.alias || ''} onBlur={(event) => { const next = event.target.value.trim() || null; if (next !== entry.alias) void work(() => aiApi(`/groups/${id}/entries/${entry.id}`, { method: 'PUT', body: JSON.stringify({ alias: next }) }), 'Public model name updated'); }} /></div><Choice label="Provider account" value={currentRoute} onChange={(value) => { const [providerModelKey, providerAccountId] = value.split('\u0000'); void work(() => aiApi(`/groups/${id}/entries/${entry.id}`, { method: 'PUT', body: JSON.stringify({ providerModelKey, providerAccountId }) }), 'Provider route updated'); }} items={routes} /><div className="flex flex-wrap items-center justify-between gap-2 md:col-span-2"><div className="md:hidden"><Status value={entry.enabled && entry.providerAvailable} label={!entry.enabled ? 'Disabled' : entry.providerAvailable ? 'Ready' : 'Unavailable'} /></div><div className="ml-auto flex gap-2"><Button variant="outline" size="sm" disabled={busy} onClick={() => void work(() => aiApi(`/groups/${id}/entries/${entry.id}`, { method: 'PUT', body: JSON.stringify({ enabled: !entry.enabled }) }), `${entry.modelName} ${entry.enabled ? 'disabled' : 'enabled'}`)}>{entry.enabled ? 'Disable' : 'Enable'}</Button><Button variant="ghost" size="sm" disabled={busy} onClick={() => setDeleteEntry(entry)}><Trash2 className="size-4" />Remove</Button></div></div></div>}
      </div>;
    })}</div> : <Empty title="No models in this group" description="Add a model and choose its exact provider account." />}
    <ConfirmDialog open={Boolean(deleteEntry)} title={`Remove ${deleteEntry?.modelName || 'model'}?`} description={`This removes the route from ${group.name}.`} confirmLabel="Remove" destructive onCancel={() => setDeleteEntry(null)} onConfirm={() => { const target = deleteEntry; setDeleteEntry(null); if (target) void work(() => aiApi(`/groups/${id}/entries/${target.id}`, { method: 'DELETE' }), `${target.modelName} removed`); }} />
  </div>;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function GroupDetails({ id }: { id: string }) {
  const [group, setGroup] = useState<GroupDetail | null>(null); const [name, setName] = useState(''); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [deleteEntry, setDeleteEntry] = useState<GroupEntry | null>(null);
  const load = useCallback(async () => { setLoading(true); try { const next = await aiApi<GroupDetail>(`/groups/${encodeURIComponent(id)}`); setGroup(next); setName(next.name); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Group unavailable'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function work(action: () => Promise<unknown>, message: string) { setBusy(true); setError(''); setNotice(''); try { await action(); setNotice(message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Group update failed'); } finally { setBusy(false); } }
  async function reorder(index: number, direction: -1 | 1) { if (!group) return; const entries = [...group.entries]; const target = index + direction; if (target < 0 || target >= entries.length) return; [entries[index], entries[target]] = [entries[target], entries[index]]; await work(() => aiApi(`/groups/${id}/entries/reorder`, { method: 'PUT', body: JSON.stringify({ entryIds: entries.map((entry) => entry.id) }) }), 'Model order updated'); }
  if (loading) return <Loading />; if (!group) return <Alert variant="destructive">{error || 'Group not found'}</Alert>;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/groups" eyebrow="groups" title={group.name} description="Ordered model routes exposed to every instance using this group." actions={<>{group.isDefault && <Badge>Default</Badge>}<Status value={group.enabledEntryCount > 0} label={`${group.enabledEntryCount} enabled`} /></>} />{error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <Card className="gap-3 p-5"><Label htmlFor="group-name">Group name</Label><div className="flex flex-col gap-2 sm:flex-row"><Input id="group-name" value={name} onChange={(event) => setName(event.target.value)} /><Button disabled={busy || !name.trim() || name.trim() === group.name} onClick={() => void work(() => aiApi(`/groups/${id}`, { method: 'PUT', body: JSON.stringify({ name: name.trim() }) }), 'Group renamed')}><Save className="size-4" />Save</Button>{!group.isDefault && <Button variant="outline" disabled={busy} onClick={() => void work(() => aiApi(`/groups/${id}/set-default`, { method: 'PUT' }), 'Default group updated')}>Make default</Button>}</div></Card>
    <div className="flex items-center justify-between gap-3"><h2 className="font-semibold">Model routes</h2><Button asChild variant="outline" size="sm"><Link href="/settings/ai/models">Add from catalog</Link></Button></div>{group.entries.length ? <div className="space-y-2">{group.entries.map((entry, index) => <Card key={entry.id} className="gap-3 p-4 sm:flex-row sm:items-center sm:justify-between"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2">{entry.modelSlug ? <Link href={`/settings/ai/models/${encodeURIComponent(entry.modelSlug)}`} className="font-semibold hover:underline">{entry.modelName}</Link> : <strong>{entry.modelName}</strong>}<Status value={entry.enabled && entry.providerAvailable} label={!entry.enabled ? 'Disabled' : entry.providerAvailable ? 'Ready' : 'Unavailable'} />{entry.needsReview && <Badge variant="destructive">Needs review</Badge>}</div><p className="mt-1 text-xs text-muted-foreground">{entry.providerName} · {entry.providerAccountNickname || entry.providerAccountId?.slice(-6) || 'No account'} · <span className="font-mono">{entry.rawModelId}</span></p>{entry.alias && <p className="mt-1 text-xs text-muted-foreground">Alias: {entry.alias}</p>}</div><div className="flex shrink-0 items-center gap-1"><Button variant="ghost" size="icon" disabled={busy || index === 0} onClick={() => void reorder(index, -1)} aria-label={`Move ${entry.modelName} up`}><ArrowUp className="size-4" /></Button><Button variant="ghost" size="icon" disabled={busy || index === group.entries.length - 1} onClick={() => void reorder(index, 1)} aria-label={`Move ${entry.modelName} down`}><ArrowDown className="size-4" /></Button><Button variant="outline" size="sm" disabled={busy} onClick={() => void work(() => aiApi(`/groups/${id}/entries/${entry.id}`, { method: 'PUT', body: JSON.stringify({ enabled: !entry.enabled }) }), `${entry.modelName} ${entry.enabled ? 'disabled' : 'enabled'}`)}>{entry.enabled ? 'Disable' : 'Enable'}</Button><Button variant="ghost" size="icon" disabled={busy} onClick={() => setDeleteEntry(entry)} aria-label={`Remove ${entry.modelName} from ${group.name}`}><Trash2 className="size-4" /></Button></div></Card>)}</div> : <Empty title="No models in this group" description="Browse the catalog and add exact provider-account routes." action={<Button asChild><Link href="/settings/ai/models">Browse models</Link></Button>} />}
    <ConfirmDialog open={Boolean(deleteEntry)} title={`Remove ${deleteEntry?.modelName || 'model'}?`} description={`This removes the model from ${group.name}.`} confirmLabel="Remove" destructive onCancel={() => setDeleteEntry(null)} onConfirm={() => { const target = deleteEntry; setDeleteEntry(null); if (target) void work(() => aiApi(`/groups/${id}/entries/${target.id}`, { method: 'DELETE' }), `${target.modelName} removed`); }} />
  </div>;
}

function NativeInstanceDetails({ id }: { id: string }) {
  const [instance, setInstance] = useState<InstanceDetail | null>(null);
  const [groups, setGroups] = useState<Group[]>([]);
  const [stats, setStats] = useState<Stats | null>(null);
  const [name, setName] = useState('');
  const [groupId, setGroupId] = useState('none');
  const [keyName, setKeyName] = useState('');
  const [allowed, setAllowed] = useState('*');
  const [revealedKey, setRevealedKey] = useState('');
  const [revokeTarget, setRevokeTarget] = useState<APIKey | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const load = useCallback(async () => {
    setLoading(true);
    try {
      const [next, nextGroups] = await Promise.all([aiApi<InstanceDetail>(`/instances/${encodeURIComponent(id)}`), aiApi<Group[]>('/groups')]);
      setInstance(next); setGroups(nextGroups); setName(next.name); setGroupId(next.modelGroupId || 'none');
      aiApi<Stats>(`/stats/instance/${encodeURIComponent(id)}?days=30`).then(setStats).catch(() => setStats(null));
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Instance unavailable'); }
    finally { setLoading(false); }
  }, [id]);
  useEffect(() => { void load(); }, [load]);
  async function work(action: () => Promise<unknown>, message: string) {
    setBusy(true); setError(''); setNotice('');
    try { await action(); setNotice(message); await load(); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Instance update failed'); }
    finally { setBusy(false); }
  }
  if (loading) return <Loading />;
  if (!instance) return <Alert variant="destructive">{error || 'Instance not found'}</Alert>;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/instances" eyebrow="instances" title={instance.name} description={`Isolated endpoint ${instance.id}`} actions={<Status value={instance.state} />} />
    {error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    {revealedKey && <Alert><div className="w-full"><strong className="text-sm">Copy this key now — it will not be shown again.</strong><div className="mt-2 flex gap-2"><Input readOnly value={revealedKey} className="font-mono" /><Button variant="outline" size="icon" aria-label="Copy API key" onClick={() => void navigator.clipboard.writeText(revealedKey)}><Copy className="size-4" /></Button></div></div></Alert>}
    <Card className="gap-4 p-5"><h2 className="font-semibold">Instance settings</h2><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="instance-name">Name</Label><Input id="instance-name" value={name} onChange={(event) => setName(event.target.value)} /></div><Choice label="Model group" value={groupId} onChange={setGroupId} items={[{ value: 'none', label: 'No group' }, ...groups.map((item) => ({ value: item.id, label: item.name }))]} /></div><Button className="self-start" disabled={busy || !name.trim() || instance.origin === 'managed'} onClick={() => void work(() => aiApi(`/instances/${id}`, { method: 'PUT', body: JSON.stringify({ name: name.trim(), modelGroupId: groupId === 'none' ? null : groupId }) }), 'Instance settings saved')}><Save className="size-4" />Save</Button></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="gap-3 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Models</h2><Badge variant="secondary">{instance.groupEntries.length + instance.models.length}</Badge></div>{instance.groupEntries.length || instance.models.length ? <div className="divide-y rounded-md border">{instance.groupEntries.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 p-3"><div><strong className="text-sm">{entry.alias || entry.modelName || entry.modelId}</strong><p className="text-xs text-muted-foreground">{entry.providerName || entry.providerId}</p></div><Status value={entry.enabled && entry.providerAvailable} /></div>)}{instance.models.map((model) => <div key={model.id} className="flex items-center justify-between gap-3 p-3"><div><strong className="text-sm">{model.alias || model.modelId}</strong><p className="text-xs text-muted-foreground">{model.providerId} · direct route</p></div><Status value={model.enabled} /></div>)}</div> : <p className="text-sm text-muted-foreground">Assign a group to expose models.</p>}</Card>
      <Card className="gap-4 p-5"><div><h2 className="font-semibold">API keys</h2><p className="mt-1 text-sm text-muted-foreground">Every key is scoped to this instance. Create as many client credentials as you need.</p></div><div className="grid gap-3"><div className="space-y-2"><Label htmlFor="instance-key-name">Key name</Label><Input id="instance-key-name" value={keyName} onChange={(event) => setKeyName(event.target.value)} placeholder="Laptop client" /></div><div className="space-y-2"><Label htmlFor="instance-key-models">Allowed models</Label><Input id="instance-key-models" value={allowed} onChange={(event) => setAllowed(event.target.value)} placeholder="* or comma-separated globs" /></div><Button className="justify-self-start" disabled={busy || !keyName.trim()} onClick={() => void work(async () => { const created = await aiApi<{ key: string }>('/keys', { method: 'POST', body: JSON.stringify({ name: keyName.trim(), instanceId: instance.id, allowedModels: allowed.split(',').map((item) => item.trim()).filter(Boolean) }) }); setRevealedKey(created.key); setKeyName(''); }, 'API key created')}><Plus className="size-4" />Create key</Button></div>{instance.keys.length ? <div className="divide-y rounded-md border">{instance.keys.map((key) => <div key={key.id} className="flex items-center justify-between gap-3 p-3"><div><strong className="text-sm">{key.name}</strong><p className="font-mono text-xs text-muted-foreground">{key.keyPreview} · {key.requestCount.toLocaleString()} requests</p></div><div className="flex items-center gap-2"><Status value={!key.revoked} label={key.revoked ? 'Revoked' : 'Active'} /><Button variant="ghost" size="icon" disabled={busy || key.revoked} onClick={() => setRevokeTarget(key)} aria-label={`Revoke ${key.name}`}><Trash2 className="size-4" /></Button></div></div>)}</div> : <p className="text-sm text-muted-foreground">No keys are bound to this instance.</p>}</Card></div>
    {stats && <div><h2 className="mb-3 font-semibold">Instance usage · last 30 days</h2><MetricCards stats={stats} /></div>}
    <ConfirmDialog open={Boolean(revokeTarget)} title={`Revoke ${revokeTarget?.name || 'key'}?`} description="Clients using this key will immediately lose access." confirmLabel="Revoke" destructive onCancel={() => setRevokeTarget(null)} onConfirm={() => { const target = revokeTarget; setRevokeTarget(null); if (target) void work(() => aiApi(`/keys/${target.id}`, { method: 'DELETE' }), `${target.name} revoked`); }} />
  </div>;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function InstanceDetails({ id }: { id: string }) {
  const [instance, setInstance] = useState<InstanceDetail | null>(null); const [groups, setGroups] = useState<Group[]>([]); const [stats, setStats] = useState<Stats | null>(null); const [name, setName] = useState(''); const [groupId, setGroupId] = useState('none'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState('');
  const load = useCallback(async () => { setLoading(true); try { const [next, nextGroups] = await Promise.all([aiApi<InstanceDetail>(`/instances/${encodeURIComponent(id)}`), aiApi<Group[]>('/groups')]); setInstance(next); setGroups(nextGroups); setName(next.name); setGroupId(next.modelGroupId || 'none'); aiApi<Stats>(`/stats/instance/${encodeURIComponent(id)}?days=30`).then(setStats).catch(() => setStats(null)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Instance unavailable'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function save() { setBusy(true); setError(''); try { await aiApi(`/instances/${id}`, { method: 'PUT', body: JSON.stringify({ name: name.trim(), modelGroupId: groupId === 'none' ? null : groupId }) }); setNotice('Instance settings saved'); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Save failed'); } finally { setBusy(false); } }
  if (loading) return <Loading />; if (!instance) return <Alert variant="destructive">{error || 'Instance not found'}</Alert>;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/instances" eyebrow="instances" title={instance.name} description={`Isolated endpoint ${instance.id}`} actions={<Status value={instance.state} />} />{error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <Card className="gap-4 p-5"><h2 className="font-semibold">Instance settings</h2><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="instance-name">Name</Label><Input id="instance-name" value={name} onChange={(event) => setName(event.target.value)} /></div><Choice label="Model group" value={groupId} onChange={setGroupId} items={[{ value: 'none', label: 'No group' }, ...groups.map((item) => ({ value: item.id, label: item.name }))]} /></div><Button className="self-start" disabled={busy || !name.trim() || instance.origin === 'managed'} onClick={() => void save()}><Save className="size-4" />Save</Button></Card>
    <div className="grid gap-4 lg:grid-cols-2"><Card className="gap-3 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Models</h2><Badge variant="secondary">{instance.groupEntries.length + instance.models.length}</Badge></div>{instance.groupEntries.length || instance.models.length ? <div className="divide-y rounded-md border">{instance.groupEntries.map((entry) => <div key={entry.id} className="flex items-center justify-between gap-3 p-3"><div><strong className="text-sm">{entry.modelName || entry.modelId}</strong><p className="text-xs text-muted-foreground">{entry.providerName || entry.providerId}</p></div><Status value={entry.enabled && entry.providerAvailable} /></div>)}{instance.models.map((model) => <div key={model.id} className="flex items-center justify-between gap-3 p-3"><div><strong className="text-sm">{model.alias || model.modelId}</strong><p className="text-xs text-muted-foreground">{model.providerId} · direct route</p></div><Status value={model.enabled} /></div>)}</div> : <p className="text-sm text-muted-foreground">Assign a group to expose models.</p>}</Card><Card className="gap-3 p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">API keys</h2><Button asChild variant="outline" size="sm"><Link href="/settings/ai/keys">Create key</Link></Button></div>{instance.keys.length ? <div className="divide-y rounded-md border">{instance.keys.map((key) => <Link key={key.id} href={`/settings/ai/keys/${encodeURIComponent(key.id)}`} className="flex items-center justify-between gap-3 p-3 hover:bg-muted/40"><div><strong className="text-sm">{key.name}</strong><p className="font-mono text-xs text-muted-foreground">{key.keyPreview}</p></div><Status value={!key.revoked} label={key.revoked ? 'Revoked' : 'Active'} /></Link>)}</div> : <p className="text-sm text-muted-foreground">No keys are bound to this instance.</p>}</Card></div>{stats && <div><h2 className="mb-3 font-semibold">Instance usage · last 30 days</h2><MetricCards stats={stats} /></div>}
  </div>;
}

// eslint-disable-next-line @typescript-eslint/no-unused-vars
function KeyDetails({ id }: { id: string }) {
  const [key, setKey] = useState<APIKey | null>(null); const [instances, setInstances] = useState<Instance[]>([]); const [stats, setStats] = useState<Stats | null>(null); const [name, setName] = useState(''); const [instanceId, setInstanceId] = useState(''); const [allowed, setAllowed] = useState('*'); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState(''); const [notice, setNotice] = useState(''); const [revoke, setRevoke] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { const [next, nextInstances] = await Promise.all([aiApi<APIKey>(`/keys/${encodeURIComponent(id)}`), aiApi<Instance[]>('/instances')]); setKey(next); setInstances(nextInstances); setName(next.name); setInstanceId(next.instanceId); setAllowed(next.allowedModels.join(', ')); aiApi<Stats>(`/stats/key/${encodeURIComponent(id)}?days=30`).then(setStats).catch(() => setStats(null)); } catch (reason) { setError(reason instanceof Error ? reason.message : 'API key unavailable'); } finally { setLoading(false); } }, [id]); useEffect(() => { void load(); }, [load]);
  async function work(action: () => Promise<unknown>, message: string) { setBusy(true); setError(''); try { await action(); setNotice(message); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'API key update failed'); } finally { setBusy(false); } }
  if (loading) return <Loading />; if (!key) return <Alert variant="destructive">{error || 'API key not found'}</Alert>;
  return <div className="space-y-6"><DetailHeader back="/settings/ai/keys" eyebrow="API keys" title={key.name} description={`Credential ${key.keyPreview}`} actions={<Status value={!key.revoked} label={key.revoked ? 'Revoked' : 'Active'} />} />{error && <Alert variant="destructive">{error}</Alert>}{notice && <Alert><Check className="size-4" />{notice}</Alert>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><Fact label="Requests" value={key.requestCount.toLocaleString()} /><Fact label="Instance" value={instances.find((item) => item.id === key.instanceId)?.name || key.instanceId} /><Fact label="Created" value={new Date(key.createdAt).toLocaleString()} /><Fact label="Last used" value={key.lastUsed ? new Date(key.lastUsed).toLocaleString() : 'Never'} /></div>
    <Card className="gap-4 p-5"><h2 className="font-semibold">Key settings</h2><div className="grid gap-4 md:grid-cols-2"><div className="space-y-2"><Label htmlFor="key-name">Name</Label><Input id="key-name" value={name} onChange={(event) => setName(event.target.value)} /></div><Choice label="Instance" value={instanceId} onChange={setInstanceId} items={instances.map((item) => ({ value: item.id, label: item.name }))} /><div className="space-y-2 md:col-span-2"><Label htmlFor="key-models">Allowed models</Label><Input id="key-models" value={allowed} onChange={(event) => setAllowed(event.target.value)} /><p className="text-xs text-muted-foreground">Comma-separated model globs. Use * for every model exposed by the instance.</p></div></div><div className="flex gap-2"><Button disabled={busy || key.revoked || !name.trim() || !instanceId} onClick={() => void work(() => aiApi(`/keys/${id}`, { method: 'PUT', body: JSON.stringify({ name: name.trim(), instanceId, allowedModels: allowed.split(',').map((item) => item.trim()).filter(Boolean) }) }), 'API key settings saved')}><Save className="size-4" />Save</Button><Button variant="destructive" disabled={busy || key.revoked} onClick={() => setRevoke(true)}>Revoke key</Button></div></Card>{stats && <><div><h2 className="mb-3 font-semibold">Key usage · last 30 days</h2><MetricCards stats={stats} /></div><div><h2 className="mb-3 font-semibold">Recent requests</h2><RecentUsageTable rows={stats.recent} /></div></>}
    <ConfirmDialog open={revoke} title={`Revoke ${key.name}?`} description="Clients using this key will immediately lose access." confirmLabel="Revoke" destructive onCancel={() => setRevoke(false)} onConfirm={() => { setRevoke(false); void work(() => aiApi(`/keys/${id}`, { method: 'DELETE' }), 'API key revoked'); }} />
  </div>;
}

function Fact({ label, value }: { label: string; value: string }) { return <Card className="gap-2 p-4"><span className="text-xs text-muted-foreground">{label}</span><strong className="break-words text-sm">{value}</strong></Card>; }
function FactRow({ label, value, mono = false }: { label: string; value: string; mono?: boolean }) { return <div className="grid gap-1 sm:grid-cols-[9rem_1fr]"><dt className="text-muted-foreground">{label}</dt><dd className={mono ? 'break-all font-mono text-xs' : ''}>{value}</dd></div>; }
function Choice({ label, value, onChange, items }: { label: string; value: string; onChange: (value: string) => void; items: Array<{ value: string; label: string }> }) { return <div className="space-y-2"><Label>{label}</Label><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="border-input bg-background text-foreground ring-offset-background"><SelectValue placeholder={label} /></SelectTrigger><SelectContent className="border-border bg-popover text-popover-foreground">{items.map((item) => <SelectItem className="focus:bg-accent focus:text-accent-foreground" key={item.value} value={item.value}>{item.label}</SelectItem>)}</SelectContent></Select></div>; }
